name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types: ["completed"]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    env:
      K8S_MANIFEST: k8s/all.yaml

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1       # ← adjust if needed

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig \
            --region eu-central-1 \
            --name ${{ secrets.EKS_CLUSTER_NAME }}

      - name: Deploy to EKS
        run: |
          kubectl apply -f $K8S_MANIFEST

      - name: Wait for backend rollout
        run: |
          kubectl rollout status deployment/backend --timeout=2m

      - name: Wait for frontend rollout
        run: |
          kubectl rollout status deployment/frontend --timeout=2m

      - name: Smoke-test frontend
        run: |
          LB=$(kubectl get svc frontend-service \
               -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
          echo "Testing http://$LB …"
          curl --fail http://$LB

